### ISSUE TITLE
Question about summit protect_dist

### ISSUE THREAD

**Issue by jenellewallace** [pfenninglab/halLiftover-postprocessing#12]
Hi, thanks for sharing this method! I just had some technical questions about how HALPER works to help me decide whether it will work for my application:
- How does HALPER ensure that the summit is preserved - is this equivalent to lifting over the summit region (summit-protect_dist to summit+protect_dist) separately from the whole peak and checking whether the result for the summit region is a single contiguous fragment?
- If I input peaks of a certain fixed width where the summits are centered, will the resulting orthologs have the summits also centered?
Thanks for any advice you can give!

**Comment by imk1** [comment]
I am so sorry that I missed this for so long.

HALPER ensures that the summit is preserved by not including peaks whose summits do not map.  HALPER does more than just ensure summit preservation -- it also ensures that the ortholog includes distance protect_dist around the summit in both directions.  If you just want summit preservation and are o.k. with not having much in your ortholog in one or both directions, you can use protect_dist 1.

If your inputs are summit-centered, the outputs may not all be summit-centered.  Whether the outputs are summit-centered depends on whether your target species has indels relative to your querey species.  For example, if the output species has a small insertion a few bases downstream of your input species, then your ortholog will probably have a summit a little upstream of center.

Please let me know if you have any follow-up questions, and I will try to respond much more promptly.

**Comment by jenellewallace** [comment]
Thank you for the details! I ended up needing some additional features and adjustments for my application so I ended up writing my own pipeline, but I appreciate you making your tool available as it helped inspire aspects of my own work.
